import nestgpu as ngpu
n=ngpu.Create('iaf_psc_exp_g',3)
print(ngpu.GetStatus(n))
print(ngpu.GetStatus(n, "V_m_rel"))
print(ngpu.GetStatus(n, "C_m"))
print(ngpu.GetStatus(n, "tau_m"))
print(ngpu.GetStatus(n, "I_syn"))
ngpu.SetStatus(n, {"C_m":120.0, "V_m_rel":17.0, "tau_m":7.0, "I_syn":600.0})
print(ngpu.GetStatus(n))
print(ngpu.GetStatus(n, "V_m_rel"))
print(ngpu.GetStatus(n, "C_m"))
print(ngpu.GetStatus(n, "tau_m"))
print(ngpu.GetStatus(n, "I_syn"))
ngpu.SetStatus(n[0:2], "V_m_rel", 10.0)
ngpu.SetStatus(n, "C_m", 80.0)
ngpu.SetStatus(n, "tau_m", 0.9)
ngpu.SetStatus(n[2:3], "I_syn", 200.0)
print(ngpu.GetStatus(n))
print(ngpu.GetStatus(n, "V_m_rel"))
print(ngpu.GetStatus(n, "C_m"))
print(ngpu.GetStatus(n, "tau_m"))
print(ngpu.GetStatus(n, "I_syn"))
print(ngpu.GetStatus(n[1:3], "V_m_rel"))
print(ngpu.GetStatus(n[0:2], "C_m"))
print(ngpu.GetStatus(n[1:3], "C_m"))
print(ngpu.GetStatus(n[1:3], "I_syn"))
print(ngpu.GetStatus(n[1:3], ["V_m_rel", "C_m"]))
