./make_brunel_mpi.sh
./make_brunel_net.sh
./make_brunel_outdegree_mpi.sh
./make_brunel_outdegree.sh
./make_brunel_vect.sh
./make_constcurr.sh
./make_setvar.sh
./make_test_aeif_cond_beta.sh
./make_test_connect.sh
./make_test_error.sh
